name: Build Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: '7.5.1'
    
    - name: Build with Gradle
      run: gradle build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SiliconFlowMod
        path: build/libs/
